export const styles: Record<string, React.CSSProperties> = {
  colorHueAlpha: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
  },
  hue: {
    width: "100%",
    position: "relative",
    borderRadius: "10px",
    padding: "0 7px",
    backgroundColor: "red",
  },
  hueArea: {
    position: "relative",
    height: "14px",
    background:
      "linear-gradient(to right, #ff0000, #ff8000, #ffff00, #80ff00, #00ff00, #00ff80, #00ffff, #0080ff, #0000ff, #8000ff, #ff00ff, #ff0080, #ff0000)",
  },
  alpha: {
    position: "relative",
    width: "100%",
    overflow: "hidden",
    borderRadius: "10px",
    height: "14px",
    cursor: "pointer",
  },
  alphaArea: {
    height: "100%",
    background:
      "linear-gradient(45deg, rgba(0, 0, 0, 0.18) 25%, transparent 25%, transparent 75%, rgba(0, 0, 0, 0.18) 75%, rgba(0, 0, 0, 0.18) 0), linear-gradient(45deg, rgba(0, 0, 0, 0.18) 25%, transparent 25%, transparent 75%, rgba(0, 0, 0, 0.18) 75%, rgba(0, 0, 0, 0.18) 0), white",
    backgroundRepeat: "repeat, repeat",
    backgroundPosition: "0px 0, 5px 5px",
    transformOrigin: "0 0 0",
    backgroundOrigin: "padding-box, padding-box",
    backgroundClip: "border-box, border-box",
    backgroundSize: "10px 10px, 10px 10px",
    boxShadow: "none",
    textShadow: "none",
    transition: "none",
    transform: "scaleX(1) scaleY(1) scaleZ(1)",
    position: "relative",
    width: "100%",
    overflow: "hidden",
    borderRadius: "10px",
  },
  gradientDegrees: {
    display: "flex",
    WebkitBoxPack: "center",
    justifyContent: "center",
    WebkitBoxAlign: "center",
    alignItems: "center",
    position: "relative",
    width: "28px",
    height: "28px",
    borderRadius: "18px",
  },
  gradientDegreeCenter: {
    position: "relative",
    width: "6px",
    height: "22px",
    pointerEvents: "none",
  },
  gradientDegreePointer: {
    position: "absolute",
    width: "10px",
    height: "10px",
    top: "-5px",
    borderRadius: "50%",
    border: "3px solid #ffffff",
    background: "transparent",
  },

  colorPickerPickerArea: {
    width: "100%",
    height: "180px",
    position: "relative",
  },
  colorPickerValueLayer: {
    height: "100%",
    width: "100%",
    background:
      "linear-gradient(to right, white 0%, rgba(255, 255, 255, 0) 100%)",
  },
  colorPickerSaturationLayer: {
    height: "100%",
    width: "100%",
    background: "linear-gradient(to bottom, rgba(0, 0, 0, 0) 0%, black 100%)",
  },

  gradient: {
    width: "100%",
    height: "14px",
    position: "relative",
    cursor: "pointer",
    borderRadius: "10px",
    padding: "0 7px",
  },
  gradientSliderContainer: {
    height: "100%",
    width: "100%",
    position: "relative",
  },

  pickerPointer: {
    position: "absolute",
    top: "1px",
    height: "12px",
    width: "12px",
    border: "1px solid #ffffff",
    background: "transparent",
    borderRadius: "50%",
    boxShadow: "0 0 4px 0 rgba(0, 0, 0, 0.3)",
    zIndex: 12,
  },
  childPoint: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    height: "3px",
    width: "3px",
    background: "#ffffff",
    borderRadius: "50%",
    opacity: 0,
    transition: "opacity 0.33s",
  },
  active: {
    opacity: 1,
  },
};
